apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-pod
    spec:
      containers:
      - name: helloworld-container
        image: xunzhaoacr1.azurecr.io/helloworld:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
